namespace Barcodes
{
	public static class EANHelper
	{
		public const string UsaCanada_Start = "00";
		public const string Usacanada_end = "13";
		public const string Instore_Start = "20";
		public const string Instore_End = "29";
		public const string France_Start = "30";
		public const string France_End = "37";
		public const string Germany_Start = "40";
		public const string Germany_End = "44";
		public const string Japan1 = "45";
		public const string RussianFederation = "46";
		public const string Taiwan = "471";
		public const string Estonia = "474";
		public const string Latvia = "475";
		public const string Lithuania = "477";
		public const string SriLanka = "479";
		public const string Philippines = "480";
		public const string Ukraine = "482";
		public const string Moldova = "484";
		public const string Armenia = "485";
		public const string Georgia = "486";
		public const string Kazakhstan = "487";
		public const string HongKong = "489";
		public const string Japan2 = "49";
		public const string UnitedKingdom = "50";
		public const string Greece = "520";
		public const string Lebanon = "528";
		public const string Cyprus = "529";
		public const string Macedonia = "531";
		public const string Malta = "535";
		public const string Ireland = "539";
		public const string Belgium_Luxembourg = "54";
		public const string Portugal = "560";
		public const string Iceland = "569";
		public const string Denmark = "57";
		public const string Poland = "590";
		public const string Romania = "594";
		public const string Hungary = "599";
		public const string SouthAfrica_Start = "600";
		public const string SouthAfrica_End = "601";
		public const string Mauritius = "609";
		public const string Morocco = "611";
		public const string Algeria = "613";
		public const string Tunisia = "619";
		public const string Egypt = "622";
		public const string Jordan = "625";
		public const string Iran = "626";
		public const string Finland = "64";
		public const string China_Start = "690";
		public const string China_End = "692";
		public const string Norway = "70";
		public const string Israel = "729";
		public const string Sweden = "73";
		public const string Guatemala = "740";
		public const string Elsalvador = "741";
		public const string Honduras = "742";
		public const string Nicaragua = "743";
		public const string Costarica = "744";
		public const string DominicanRepublic = "746";
		public const string Mexico = "750";
		public const string Venezuela = "759";
		public const string Switzerland = "76";
		public const string Colombia = "770";
		public const string Uruguay = "773";
		public const string Peru1 = "775";
		public const string Bolivia = "777";
		public const string Argentina = "779";
		public const string Chile = "780";
		public const string Paraguay = "784";
		public const string Peru2 = "785";
		public const string Ecuador = "786";
		public const string Brazil = "789";
		public const string Italy_Start = "80";
		public const string Italy_End = "83";
		public const string Spain = "84";
		public const string Cuba = "850";
		public const string Slovakia = "858";
		public const string CzechRepublic = "859";
		public const string Yugloslavia = "860";
		public const string Turkey = "869";
		public const string Netherlands = "87";
		public const string SouthKorea = "880";
		public const string Thailand = "885";
		public const string Singapore = "888";
		public const string India = "890";
		public const string Vietnam = "893";
		public const string Indonesia = "899";
		public const string Austria_Start = "90";
		public const string Austria_End = "91";
		public const string Australia = "93";
		public const string NewZealand = "94";
		public const string Malaysia = "955";
		public const string ISSN = "977";//International Standard Serial Number for Periodicals
		public const string ISBN = "978";// International Standard Book Numbering (ISBN)
		public const string ISMN = "979";//International Standard Music Number (ISMN)
		public const string RefundReceipts = "980";
		public const string CommonCurrencyCoupons_Start = "981";
		public const string CommonCurrencyCoupons_End = "982";
		public const string Coupons = "99";

		public const string Upc_Regular0 = "0";
		public const string Upc_InstoreWeight = "2";
		public const string Upc_DrugHealth = "3";
		public const string Upc_InstoreNonFood = "4";
		public const string Upc_Coupons = "5";
		public const string Upc_Regular7 = "7";

		public const string Upc5_Dollars = "50000";
		public const string Upc5_Pounds = "0";
		public const string Upc5_NoSrp = "90000";
		public const string Upc5_NoCost = "99991";
		public const string Upc5_Used = "99990";
	}
}